//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 10/19/2012 6:52:22 PM
namespace Singly.Tests.Singly
{
    
    /// <summary>
    /// There are no comments for SinglyContext in the schema.
    /// </summary>
    public partial class SinglyContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SinglyContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SinglyContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("Singly", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Singly.Tests.Singly", typeName.Substring(6)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Singly.Tests.Singly", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Singly.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Photos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Photo> Photos
        {
            get
            {
                if ((this._Photos == null))
                {
                    this._Photos = base.CreateQuery<Photo>("Photos");
                }
                return this._Photos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Photo> _Photos;
        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Contact> Contacts
        {
            get
            {
                if ((this._Contacts == null))
                {
                    this._Contacts = base.CreateQuery<Contact>("Contacts");
                }
                return this._Contacts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Contact> _Contacts;
        /// <summary>
        /// There are no comments for Checkins in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Checking> Checkins
        {
            get
            {
                if ((this._Checkins == null))
                {
                    this._Checkins = base.CreateQuery<Checking>("Checkins");
                }
                return this._Checkins;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Checking> _Checkins;
        /// <summary>
        /// There are no comments for News in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<News> News
        {
            get
            {
                if ((this._News == null))
                {
                    this._News = base.CreateQuery<News>("News");
                }
                return this._News;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<News> _News;
        /// <summary>
        /// There are no comments for Videos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Video> Videos
        {
            get
            {
                if ((this._Videos == null))
                {
                    this._Videos = base.CreateQuery<Video>("Videos");
                }
                return this._Videos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Video> _Videos;
        /// <summary>
        /// There are no comments for Statuses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Status> Statuses
        {
            get
            {
                if ((this._Statuses == null))
                {
                    this._Statuses = base.CreateQuery<Status>("Statuses");
                }
                return this._Statuses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Status> _Statuses;
        /// <summary>
        /// There are no comments for Photos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPhotos(Photo photo)
        {
            base.AddObject("Photos", photo);
        }
        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToContacts(Contact contact)
        {
            base.AddObject("Contacts", contact);
        }
        /// <summary>
        /// There are no comments for Checkins in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCheckins(Checking checking)
        {
            base.AddObject("Checkins", checking);
        }
        /// <summary>
        /// There are no comments for News in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNews(News news)
        {
            base.AddObject("News", news);
        }
        /// <summary>
        /// There are no comments for Videos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToVideos(Video video)
        {
            base.AddObject("Videos", video);
        }
        /// <summary>
        /// There are no comments for Statuses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStatuses(Status status)
        {
            base.AddObject("Statuses", status);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public virtual void UseJsonFormatWithDefaultServiceModel()
        {
            this.Format.UseJson(DefaultModelResolver.Instance);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class DefaultModelResolver
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString(ModelEdmx);
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelEdmx = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"Singly\" xmlns=\"http://schemas.microsoft.com/ado/2006/04/edm\"><EntityT" +
                "ype Name=\"Type\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Ed" +
                "m.String\" Nullable=\"false\" /><Property Name=\"Date\" Type=\"Edm.DateTime\" Nullable=" +
                "\"false\" /><Property Name=\"Data\" Type=\"Edm.String\" /></EntityType><EntityType Nam" +
                "e=\"Photo\" BaseType=\"Singly.Type\"><Property Name=\"Oembed\" Type=\"Singly.PhotoOembe" +
                "d\" Nullable=\"false\" /></EntityType><ComplexType Name=\"PhotoOembed\"><Property Nam" +
                "e=\"Url\" Type=\"Edm.String\" /><Property Name=\"Width\" Type=\"Edm.Int32\" /><Property " +
                "Name=\"Height\" Type=\"Edm.Int32\" /><Property Name=\"Type\" Type=\"Edm.String\" /><Prop" +
                "erty Name=\"Version\" Type=\"Edm.String\" /><Property Name=\"Title\" Type=\"Edm.String\"" +
                " /><Property Name=\"AuthorName\" Type=\"Edm.String\" /><Property Name=\"AuthorUrl\" Ty" +
                "pe=\"Edm.String\" /><Property Name=\"ProviderName\" Type=\"Edm.String\" /><Property Na" +
                "me=\"ProviderUrl\" Type=\"Edm.String\" /><Property Name=\"CacheAge\" Type=\"Edm.String\"" +
                " /><Property Name=\"ThumbnailUrl\" Type=\"Edm.String\" /><Property Name=\"ThumbnailWi" +
                "dth\" Type=\"Edm.Int32\" /><Property Name=\"ThumbnailHeight\" Type=\"Edm.Int32\" /></Co" +
                "mplexType><EntityType Name=\"Contact\" BaseType=\"Singly.Type\"><Property Name=\"Oemb" +
                "ed\" Type=\"Singly.ContactOembed\" Nullable=\"false\" /></EntityType><ComplexType Nam" +
                "e=\"ContactOembed\"><Property Name=\"Type\" Type=\"Edm.String\" /><Property Name=\"Vers" +
                "ion\" Type=\"Edm.String\" /><Property Name=\"Title\" Type=\"Edm.String\" /><Property Na" +
                "me=\"Description\" Type=\"Edm.String\" /><Property Name=\"Url\" Type=\"Edm.String\" /><P" +
                "roperty Name=\"ThumbnailUrl\" Type=\"Edm.String\" /><Property Name=\"ProviderName\" Ty" +
                "pe=\"Edm.String\" /><Property Name=\"SourceName\" Type=\"Edm.String\" /></ComplexType>" +
                "<ComplexType Name=\"Oembed\"><Property Name=\"Type\" Type=\"Edm.String\" /><Property N" +
                "ame=\"Version\" Type=\"Edm.String\" /><Property Name=\"Title\" Type=\"Edm.String\" /><Pr" +
                "operty Name=\"AuthorName\" Type=\"Edm.String\" /><Property Name=\"AuthorUrl\" Type=\"Ed" +
                "m.String\" /><Property Name=\"ProviderName\" Type=\"Edm.String\" /><Property Name=\"Pr" +
                "oviderUrl\" Type=\"Edm.String\" /><Property Name=\"CacheAge\" Type=\"Edm.String\" /><Pr" +
                "operty Name=\"ThumbnailUrl\" Type=\"Edm.String\" /><Property Name=\"ThumbnailWidth\" T" +
                "ype=\"Edm.Int32\" /><Property Name=\"ThumbnailHeight\" Type=\"Edm.Int32\" /><Property " +
                "Name=\"SourceName\" Type=\"Edm.String\" /></ComplexType><EntityType Name=\"Checking\" " +
                "BaseType=\"Singly.Type\"><Property Name=\"Oembed\" Type=\"Singly.Oembed\" Nullable=\"fa" +
                "lse\" /></EntityType><EntityType Name=\"News\" BaseType=\"Singly.Type\"><Property Nam" +
                "e=\"Oembed\" Type=\"Singly.Oembed\" Nullable=\"false\" /></EntityType><EntityType Name" +
                "=\"Video\" BaseType=\"Singly.Type\"><Property Name=\"Oembed\" Type=\"Singly.VideoOembed" +
                "\" Nullable=\"false\" /></EntityType><ComplexType Name=\"VideoOembed\"><Property Name" +
                "=\"Html\" Type=\"Edm.String\" /><Property Name=\"Width\" Type=\"Edm.Int32\" /><Property " +
                "Name=\"Height\" Type=\"Edm.Int32\" /><Property Name=\"Type\" Type=\"Edm.String\" /><Prop" +
                "erty Name=\"Version\" Type=\"Edm.String\" /><Property Name=\"Title\" Type=\"Edm.String\"" +
                " /><Property Name=\"AuthorName\" Type=\"Edm.String\" /><Property Name=\"AuthorUrl\" Ty" +
                "pe=\"Edm.String\" /><Property Name=\"ProviderName\" Type=\"Edm.String\" /><Property Na" +
                "me=\"ProviderUrl\" Type=\"Edm.String\" /><Property Name=\"CacheAge\" Type=\"Edm.String\"" +
                " /><Property Name=\"ThumbnailUrl\" Type=\"Edm.String\" /><Property Name=\"ThumbnailWi" +
                "dth\" Type=\"Edm.Int32\" /><Property Name=\"ThumbnailHeight\" Type=\"Edm.Int32\" /><Pro" +
                "perty Name=\"SourceName\" Type=\"Edm.String\" /></ComplexType><ComplexType Name=\"Tex" +
                "tOembed\"><Property Name=\"Text\" Type=\"Edm.String\" /><Property Name=\"SourceName\" T" +
                "ype=\"Edm.String\" /><Property Name=\"Type\" Type=\"Edm.String\" /><Property Name=\"Ver" +
                "sion\" Type=\"Edm.String\" /></ComplexType><EntityType Name=\"Status\" BaseType=\"Sing" +
                "ly.Type\"><Property Name=\"Oembed\" Type=\"Singly.TextOembed\" Nullable=\"false\" /></E" +
                "ntityType><EntityContainer Name=\"SinglyContext\" m:IsDefaultEntityContainer=\"true" +
                "\"><EntitySet Name=\"Photos\" EntityType=\"Singly.Photo\" /><EntitySet Name=\"Contacts" +
                "\" EntityType=\"Singly.Contact\" /><EntitySet Name=\"Checkins\" EntityType=\"Singly.Ch" +
                "ecking\" /><EntitySet Name=\"News\" EntityType=\"Singly.News\" /><EntitySet Name=\"Vid" +
                "eos\" EntityType=\"Singly.Video\" /><EntitySet Name=\"Statuses\" EntityType=\"Singly.S" +
                "tatus\" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel Instance
            {
                get
                {
                    return ParsedModel;
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString(string edmxToParse)
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for Singly.Type in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Type : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Type object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Type CreateType(string ID, global::System.DateTime date)
        {
            Type type = new Type();
            type.Id = ID;
            type.Date = date;
            return type;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this.OnDataChanging(value);
                this._Data = value;
                this.OnDataChanged();
                this.OnPropertyChanged("Data");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Data;
        partial void OnDataChanging(string value);
        partial void OnDataChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType Singly.PhotoOembed in the schema.
    /// </summary>
    public partial class PhotoOembed : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
                this.OnPropertyChanged("Url");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// There are no comments for Property Width in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                this.OnWidthChanging(value);
                this._Width = value;
                this.OnWidthChanged();
                this.OnPropertyChanged("Width");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Width;
        partial void OnWidthChanging(global::System.Nullable<int> value);
        partial void OnWidthChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
                this.OnPropertyChanged("Height");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Height;
        partial void OnHeightChanging(global::System.Nullable<int> value);
        partial void OnHeightChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property AuthorName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuthorName
        {
            get
            {
                return this._AuthorName;
            }
            set
            {
                this.OnAuthorNameChanging(value);
                this._AuthorName = value;
                this.OnAuthorNameChanged();
                this.OnPropertyChanged("AuthorName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuthorName;
        partial void OnAuthorNameChanging(string value);
        partial void OnAuthorNameChanged();
        /// <summary>
        /// There are no comments for Property AuthorUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuthorUrl
        {
            get
            {
                return this._AuthorUrl;
            }
            set
            {
                this.OnAuthorUrlChanging(value);
                this._AuthorUrl = value;
                this.OnAuthorUrlChanged();
                this.OnPropertyChanged("AuthorUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuthorUrl;
        partial void OnAuthorUrlChanging(string value);
        partial void OnAuthorUrlChanged();
        /// <summary>
        /// There are no comments for Property ProviderName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProviderName
        {
            get
            {
                return this._ProviderName;
            }
            set
            {
                this.OnProviderNameChanging(value);
                this._ProviderName = value;
                this.OnProviderNameChanged();
                this.OnPropertyChanged("ProviderName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProviderName;
        partial void OnProviderNameChanging(string value);
        partial void OnProviderNameChanged();
        /// <summary>
        /// There are no comments for Property ProviderUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProviderUrl
        {
            get
            {
                return this._ProviderUrl;
            }
            set
            {
                this.OnProviderUrlChanging(value);
                this._ProviderUrl = value;
                this.OnProviderUrlChanged();
                this.OnPropertyChanged("ProviderUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProviderUrl;
        partial void OnProviderUrlChanging(string value);
        partial void OnProviderUrlChanged();
        /// <summary>
        /// There are no comments for Property CacheAge in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CacheAge
        {
            get
            {
                return this._CacheAge;
            }
            set
            {
                this.OnCacheAgeChanging(value);
                this._CacheAge = value;
                this.OnCacheAgeChanged();
                this.OnPropertyChanged("CacheAge");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CacheAge;
        partial void OnCacheAgeChanging(string value);
        partial void OnCacheAgeChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ThumbnailUrl
        {
            get
            {
                return this._ThumbnailUrl;
            }
            set
            {
                this.OnThumbnailUrlChanging(value);
                this._ThumbnailUrl = value;
                this.OnThumbnailUrlChanged();
                this.OnPropertyChanged("ThumbnailUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ThumbnailUrl;
        partial void OnThumbnailUrlChanging(string value);
        partial void OnThumbnailUrlChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailWidth in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ThumbnailWidth
        {
            get
            {
                return this._ThumbnailWidth;
            }
            set
            {
                this.OnThumbnailWidthChanging(value);
                this._ThumbnailWidth = value;
                this.OnThumbnailWidthChanged();
                this.OnPropertyChanged("ThumbnailWidth");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ThumbnailWidth;
        partial void OnThumbnailWidthChanging(global::System.Nullable<int> value);
        partial void OnThumbnailWidthChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailHeight in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ThumbnailHeight
        {
            get
            {
                return this._ThumbnailHeight;
            }
            set
            {
                this.OnThumbnailHeightChanging(value);
                this._ThumbnailHeight = value;
                this.OnThumbnailHeightChanged();
                this.OnPropertyChanged("ThumbnailHeight");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ThumbnailHeight;
        partial void OnThumbnailHeightChanging(global::System.Nullable<int> value);
        partial void OnThumbnailHeightChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Singly.Photo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Photos")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Photo : Type
    {
        /// <summary>
        /// Create a new Photo object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="oembed">Initial value of Oembed.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Photo CreatePhoto(string ID, global::System.DateTime date, PhotoOembed oembed)
        {
            Photo photo = new Photo();
            photo.Id = ID;
            photo.Date = date;
            if ((oembed == null))
            {
                throw new global::System.ArgumentNullException("oembed");
            }
            photo.Oembed = oembed;
            return photo;
        }
        /// <summary>
        /// There are no comments for Property Oembed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PhotoOembed Oembed
        {
            get
            {
                if (((this._Oembed == null) 
                            && (this._OembedInitialized != true)))
                {
                    this._Oembed = new PhotoOembed();
                    this._OembedInitialized = true;
                }
                return this._Oembed;
            }
            set
            {
                this.OnOembedChanging(value);
                this._Oembed = value;
                this._OembedInitialized = true;
                this.OnOembedChanged();
                this.OnPropertyChanged("Oembed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PhotoOembed _Oembed;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _OembedInitialized;
        partial void OnOembedChanging(PhotoOembed value);
        partial void OnOembedChanged();
    }
    /// <summary>
    /// There are no comments for ComplexType Singly.ContactOembed in the schema.
    /// </summary>
    public partial class ContactOembed : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
                this.OnPropertyChanged("Url");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ThumbnailUrl
        {
            get
            {
                return this._ThumbnailUrl;
            }
            set
            {
                this.OnThumbnailUrlChanging(value);
                this._ThumbnailUrl = value;
                this.OnThumbnailUrlChanged();
                this.OnPropertyChanged("ThumbnailUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ThumbnailUrl;
        partial void OnThumbnailUrlChanging(string value);
        partial void OnThumbnailUrlChanged();
        /// <summary>
        /// There are no comments for Property ProviderName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProviderName
        {
            get
            {
                return this._ProviderName;
            }
            set
            {
                this.OnProviderNameChanging(value);
                this._ProviderName = value;
                this.OnProviderNameChanged();
                this.OnPropertyChanged("ProviderName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProviderName;
        partial void OnProviderNameChanging(string value);
        partial void OnProviderNameChanged();
        /// <summary>
        /// There are no comments for Property SourceName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SourceName
        {
            get
            {
                return this._SourceName;
            }
            set
            {
                this.OnSourceNameChanging(value);
                this._SourceName = value;
                this.OnSourceNameChanged();
                this.OnPropertyChanged("SourceName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SourceName;
        partial void OnSourceNameChanging(string value);
        partial void OnSourceNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Singly.Contact in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Contacts")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Contact : Type
    {
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="oembed">Initial value of Oembed.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Contact CreateContact(string ID, global::System.DateTime date, ContactOembed oembed)
        {
            Contact contact = new Contact();
            contact.Id = ID;
            contact.Date = date;
            if ((oembed == null))
            {
                throw new global::System.ArgumentNullException("oembed");
            }
            contact.Oembed = oembed;
            return contact;
        }
        /// <summary>
        /// There are no comments for Property Oembed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ContactOembed Oembed
        {
            get
            {
                if (((this._Oembed == null) 
                            && (this._OembedInitialized != true)))
                {
                    this._Oembed = new ContactOembed();
                    this._OembedInitialized = true;
                }
                return this._Oembed;
            }
            set
            {
                this.OnOembedChanging(value);
                this._Oembed = value;
                this._OembedInitialized = true;
                this.OnOembedChanged();
                this.OnPropertyChanged("Oembed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ContactOembed _Oembed;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _OembedInitialized;
        partial void OnOembedChanging(ContactOembed value);
        partial void OnOembedChanged();
    }
    /// <summary>
    /// There are no comments for ComplexType Singly.Oembed in the schema.
    /// </summary>
    public partial class Oembed : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property AuthorName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuthorName
        {
            get
            {
                return this._AuthorName;
            }
            set
            {
                this.OnAuthorNameChanging(value);
                this._AuthorName = value;
                this.OnAuthorNameChanged();
                this.OnPropertyChanged("AuthorName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuthorName;
        partial void OnAuthorNameChanging(string value);
        partial void OnAuthorNameChanged();
        /// <summary>
        /// There are no comments for Property AuthorUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuthorUrl
        {
            get
            {
                return this._AuthorUrl;
            }
            set
            {
                this.OnAuthorUrlChanging(value);
                this._AuthorUrl = value;
                this.OnAuthorUrlChanged();
                this.OnPropertyChanged("AuthorUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuthorUrl;
        partial void OnAuthorUrlChanging(string value);
        partial void OnAuthorUrlChanged();
        /// <summary>
        /// There are no comments for Property ProviderName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProviderName
        {
            get
            {
                return this._ProviderName;
            }
            set
            {
                this.OnProviderNameChanging(value);
                this._ProviderName = value;
                this.OnProviderNameChanged();
                this.OnPropertyChanged("ProviderName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProviderName;
        partial void OnProviderNameChanging(string value);
        partial void OnProviderNameChanged();
        /// <summary>
        /// There are no comments for Property ProviderUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProviderUrl
        {
            get
            {
                return this._ProviderUrl;
            }
            set
            {
                this.OnProviderUrlChanging(value);
                this._ProviderUrl = value;
                this.OnProviderUrlChanged();
                this.OnPropertyChanged("ProviderUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProviderUrl;
        partial void OnProviderUrlChanging(string value);
        partial void OnProviderUrlChanged();
        /// <summary>
        /// There are no comments for Property CacheAge in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CacheAge
        {
            get
            {
                return this._CacheAge;
            }
            set
            {
                this.OnCacheAgeChanging(value);
                this._CacheAge = value;
                this.OnCacheAgeChanged();
                this.OnPropertyChanged("CacheAge");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CacheAge;
        partial void OnCacheAgeChanging(string value);
        partial void OnCacheAgeChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ThumbnailUrl
        {
            get
            {
                return this._ThumbnailUrl;
            }
            set
            {
                this.OnThumbnailUrlChanging(value);
                this._ThumbnailUrl = value;
                this.OnThumbnailUrlChanged();
                this.OnPropertyChanged("ThumbnailUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ThumbnailUrl;
        partial void OnThumbnailUrlChanging(string value);
        partial void OnThumbnailUrlChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailWidth in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ThumbnailWidth
        {
            get
            {
                return this._ThumbnailWidth;
            }
            set
            {
                this.OnThumbnailWidthChanging(value);
                this._ThumbnailWidth = value;
                this.OnThumbnailWidthChanged();
                this.OnPropertyChanged("ThumbnailWidth");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ThumbnailWidth;
        partial void OnThumbnailWidthChanging(global::System.Nullable<int> value);
        partial void OnThumbnailWidthChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailHeight in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ThumbnailHeight
        {
            get
            {
                return this._ThumbnailHeight;
            }
            set
            {
                this.OnThumbnailHeightChanging(value);
                this._ThumbnailHeight = value;
                this.OnThumbnailHeightChanged();
                this.OnPropertyChanged("ThumbnailHeight");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ThumbnailHeight;
        partial void OnThumbnailHeightChanging(global::System.Nullable<int> value);
        partial void OnThumbnailHeightChanged();
        /// <summary>
        /// There are no comments for Property SourceName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SourceName
        {
            get
            {
                return this._SourceName;
            }
            set
            {
                this.OnSourceNameChanging(value);
                this._SourceName = value;
                this.OnSourceNameChanged();
                this.OnPropertyChanged("SourceName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SourceName;
        partial void OnSourceNameChanging(string value);
        partial void OnSourceNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Singly.Checking in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Checkins")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Checking : Type
    {
        /// <summary>
        /// Create a new Checking object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="oembed">Initial value of Oembed.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Checking CreateChecking(string ID, global::System.DateTime date, Oembed oembed)
        {
            Checking checking = new Checking();
            checking.Id = ID;
            checking.Date = date;
            if ((oembed == null))
            {
                throw new global::System.ArgumentNullException("oembed");
            }
            checking.Oembed = oembed;
            return checking;
        }
        /// <summary>
        /// There are no comments for Property Oembed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Oembed Oembed
        {
            get
            {
                if (((this._Oembed == null) 
                            && (this._OembedInitialized != true)))
                {
                    this._Oembed = new Oembed();
                    this._OembedInitialized = true;
                }
                return this._Oembed;
            }
            set
            {
                this.OnOembedChanging(value);
                this._Oembed = value;
                this._OembedInitialized = true;
                this.OnOembedChanged();
                this.OnPropertyChanged("Oembed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Oembed _Oembed;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _OembedInitialized;
        partial void OnOembedChanging(Oembed value);
        partial void OnOembedChanged();
    }
    /// <summary>
    /// There are no comments for Singly.News in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("News")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class News : Type
    {
        /// <summary>
        /// Create a new News object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="oembed">Initial value of Oembed.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static News CreateNews(string ID, global::System.DateTime date, Oembed oembed)
        {
            News news = new News();
            news.Id = ID;
            news.Date = date;
            if ((oembed == null))
            {
                throw new global::System.ArgumentNullException("oembed");
            }
            news.Oembed = oembed;
            return news;
        }
        /// <summary>
        /// There are no comments for Property Oembed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Oembed Oembed
        {
            get
            {
                if (((this._Oembed == null) 
                            && (this._OembedInitialized != true)))
                {
                    this._Oembed = new Oembed();
                    this._OembedInitialized = true;
                }
                return this._Oembed;
            }
            set
            {
                this.OnOembedChanging(value);
                this._Oembed = value;
                this._OembedInitialized = true;
                this.OnOembedChanged();
                this.OnPropertyChanged("Oembed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Oembed _Oembed;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _OembedInitialized;
        partial void OnOembedChanging(Oembed value);
        partial void OnOembedChanged();
    }
    /// <summary>
    /// There are no comments for ComplexType Singly.VideoOembed in the schema.
    /// </summary>
    public partial class VideoOembed : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Html in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Html
        {
            get
            {
                return this._Html;
            }
            set
            {
                this.OnHtmlChanging(value);
                this._Html = value;
                this.OnHtmlChanged();
                this.OnPropertyChanged("Html");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Html;
        partial void OnHtmlChanging(string value);
        partial void OnHtmlChanged();
        /// <summary>
        /// There are no comments for Property Width in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                this.OnWidthChanging(value);
                this._Width = value;
                this.OnWidthChanged();
                this.OnPropertyChanged("Width");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Width;
        partial void OnWidthChanging(global::System.Nullable<int> value);
        partial void OnWidthChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
                this.OnPropertyChanged("Height");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Height;
        partial void OnHeightChanging(global::System.Nullable<int> value);
        partial void OnHeightChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property AuthorName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuthorName
        {
            get
            {
                return this._AuthorName;
            }
            set
            {
                this.OnAuthorNameChanging(value);
                this._AuthorName = value;
                this.OnAuthorNameChanged();
                this.OnPropertyChanged("AuthorName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuthorName;
        partial void OnAuthorNameChanging(string value);
        partial void OnAuthorNameChanged();
        /// <summary>
        /// There are no comments for Property AuthorUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuthorUrl
        {
            get
            {
                return this._AuthorUrl;
            }
            set
            {
                this.OnAuthorUrlChanging(value);
                this._AuthorUrl = value;
                this.OnAuthorUrlChanged();
                this.OnPropertyChanged("AuthorUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuthorUrl;
        partial void OnAuthorUrlChanging(string value);
        partial void OnAuthorUrlChanged();
        /// <summary>
        /// There are no comments for Property ProviderName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProviderName
        {
            get
            {
                return this._ProviderName;
            }
            set
            {
                this.OnProviderNameChanging(value);
                this._ProviderName = value;
                this.OnProviderNameChanged();
                this.OnPropertyChanged("ProviderName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProviderName;
        partial void OnProviderNameChanging(string value);
        partial void OnProviderNameChanged();
        /// <summary>
        /// There are no comments for Property ProviderUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProviderUrl
        {
            get
            {
                return this._ProviderUrl;
            }
            set
            {
                this.OnProviderUrlChanging(value);
                this._ProviderUrl = value;
                this.OnProviderUrlChanged();
                this.OnPropertyChanged("ProviderUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProviderUrl;
        partial void OnProviderUrlChanging(string value);
        partial void OnProviderUrlChanged();
        /// <summary>
        /// There are no comments for Property CacheAge in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CacheAge
        {
            get
            {
                return this._CacheAge;
            }
            set
            {
                this.OnCacheAgeChanging(value);
                this._CacheAge = value;
                this.OnCacheAgeChanged();
                this.OnPropertyChanged("CacheAge");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CacheAge;
        partial void OnCacheAgeChanging(string value);
        partial void OnCacheAgeChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailUrl in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ThumbnailUrl
        {
            get
            {
                return this._ThumbnailUrl;
            }
            set
            {
                this.OnThumbnailUrlChanging(value);
                this._ThumbnailUrl = value;
                this.OnThumbnailUrlChanged();
                this.OnPropertyChanged("ThumbnailUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ThumbnailUrl;
        partial void OnThumbnailUrlChanging(string value);
        partial void OnThumbnailUrlChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailWidth in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ThumbnailWidth
        {
            get
            {
                return this._ThumbnailWidth;
            }
            set
            {
                this.OnThumbnailWidthChanging(value);
                this._ThumbnailWidth = value;
                this.OnThumbnailWidthChanged();
                this.OnPropertyChanged("ThumbnailWidth");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ThumbnailWidth;
        partial void OnThumbnailWidthChanging(global::System.Nullable<int> value);
        partial void OnThumbnailWidthChanged();
        /// <summary>
        /// There are no comments for Property ThumbnailHeight in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ThumbnailHeight
        {
            get
            {
                return this._ThumbnailHeight;
            }
            set
            {
                this.OnThumbnailHeightChanging(value);
                this._ThumbnailHeight = value;
                this.OnThumbnailHeightChanged();
                this.OnPropertyChanged("ThumbnailHeight");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ThumbnailHeight;
        partial void OnThumbnailHeightChanging(global::System.Nullable<int> value);
        partial void OnThumbnailHeightChanged();
        /// <summary>
        /// There are no comments for Property SourceName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SourceName
        {
            get
            {
                return this._SourceName;
            }
            set
            {
                this.OnSourceNameChanging(value);
                this._SourceName = value;
                this.OnSourceNameChanged();
                this.OnPropertyChanged("SourceName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SourceName;
        partial void OnSourceNameChanging(string value);
        partial void OnSourceNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Singly.Video in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Videos")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Video : Type
    {
        /// <summary>
        /// Create a new Video object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="oembed">Initial value of Oembed.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Video CreateVideo(string ID, global::System.DateTime date, VideoOembed oembed)
        {
            Video video = new Video();
            video.Id = ID;
            video.Date = date;
            if ((oembed == null))
            {
                throw new global::System.ArgumentNullException("oembed");
            }
            video.Oembed = oembed;
            return video;
        }
        /// <summary>
        /// There are no comments for Property Oembed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public VideoOembed Oembed
        {
            get
            {
                if (((this._Oembed == null) 
                            && (this._OembedInitialized != true)))
                {
                    this._Oembed = new VideoOembed();
                    this._OembedInitialized = true;
                }
                return this._Oembed;
            }
            set
            {
                this.OnOembedChanging(value);
                this._Oembed = value;
                this._OembedInitialized = true;
                this.OnOembedChanged();
                this.OnPropertyChanged("Oembed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private VideoOembed _Oembed;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _OembedInitialized;
        partial void OnOembedChanging(VideoOembed value);
        partial void OnOembedChanged();
    }
    /// <summary>
    /// There are no comments for ComplexType Singly.TextOembed in the schema.
    /// </summary>
    public partial class TextOembed : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Text in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Text
        {
            get
            {
                return this._Text;
            }
            set
            {
                this.OnTextChanging(value);
                this._Text = value;
                this.OnTextChanged();
                this.OnPropertyChanged("Text");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Text;
        partial void OnTextChanging(string value);
        partial void OnTextChanged();
        /// <summary>
        /// There are no comments for Property SourceName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SourceName
        {
            get
            {
                return this._SourceName;
            }
            set
            {
                this.OnSourceNameChanging(value);
                this._SourceName = value;
                this.OnSourceNameChanged();
                this.OnPropertyChanged("SourceName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SourceName;
        partial void OnSourceNameChanging(string value);
        partial void OnSourceNameChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Singly.Status in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Statuses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Status : Type
    {
        /// <summary>
        /// Create a new Status object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="oembed">Initial value of Oembed.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Status CreateStatus(string ID, global::System.DateTime date, TextOembed oembed)
        {
            Status status = new Status();
            status.Id = ID;
            status.Date = date;
            if ((oembed == null))
            {
                throw new global::System.ArgumentNullException("oembed");
            }
            status.Oembed = oembed;
            return status;
        }
        /// <summary>
        /// There are no comments for Property Oembed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TextOembed Oembed
        {
            get
            {
                if (((this._Oembed == null) 
                            && (this._OembedInitialized != true)))
                {
                    this._Oembed = new TextOembed();
                    this._OembedInitialized = true;
                }
                return this._Oembed;
            }
            set
            {
                this.OnOembedChanging(value);
                this._Oembed = value;
                this._OembedInitialized = true;
                this.OnOembedChanged();
                this.OnPropertyChanged("Oembed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private TextOembed _Oembed;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _OembedInitialized;
        partial void OnOembedChanging(TextOembed value);
        partial void OnOembedChanged();
    }
}
